name: Auto Pull Request Workflow

on:
  push:
    branches:
      - main

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Extract Git Commit Data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Debug Current Branch
        run: |
          echo "Current Branch: ${{ github.ref_name }}"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: production-promotion