name: Auto Pull Request Workflow

on:
  push:
    branches:
      - main

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Extract Git Commit Data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Debug Current Branch
        run: |
          echo "Current Branch: ${{ github.ref_name }}"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: production-promotion

      - name: Debug Pull Request Number
        run: |
          echo "Pull Request Number: ${{ steps.create-pr.outputs.pull-request-number }}"

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.PR_DEMO }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}

      - name: Debug Approval Status
        run: |
          echo "Approval Status: ${{ steps.approve.outputs.status }}"

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash
          
      - name: Debug Merge Status
        run: |
          echo "Merge Status: ${{ steps.merge.outputs.status }}"